development:
  adapter: postgresql
  encoding: unicode
  database: rfp_poc
  pool: 10
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: rfp_poc_prod
  pool: 10
  username: postgres
  password: password
  host: localhost
  port: 5432
